sonar.projectKey=vsmetgudmediaportal

sonar.projectKey=vsmetgud-media-portal

sonar.projectName=vsmetgud-media-portal

sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=node_modules/**,coverage/**

sonar.sourceEncoding=UTF-8