replicaCount: 1

image:
  repository: vsmetgud/media-portal
  tag: "e7098df961ceacf614d2b3ad3fe1ccb63b9d9f04"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30080

persistence:
  enabled: true
  mountPath: /usr/src/app/media
  hostPath: /media/sf_e-drive
  #hostPath: /mnt/media

ingress:
  enabled: false
  className: nginx
  host: vsmetgud.online

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector:
  kubernetes.io/hostname: k8s-worker

autoscaling:
  enabled: false
